-- PostgreSQL design for Project 1; no running pipeline is required.
CREATE TABLE dim_game (
  game_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appid INTEGER NOT NULL,
  game_name VARCHAR(255) NOT NULL,
  release_date DATE,
  current_price DECIMAL(10,2) CHECK (current_price >= 0), -- USD in this snapshot
  valid_from TIMESTAMP NOT NULL,
  valid_to TIMESTAMP,
  is_current BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (appid, valid_from),
  CHECK (valid_to IS NULL OR valid_to > valid_from),
  CHECK (is_current = (valid_to IS NULL))
);
-- Historical versions may share an appid; only the current one is unique.
CREATE UNIQUE INDEX one_current_game_per_appid
  ON dim_game (appid) WHERE is_current;

CREATE TABLE dim_date (
  date_key INTEGER PRIMARY KEY, -- YYYYMM
  month_start DATE NOT NULL UNIQUE,
  month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
  quarter SMALLINT NOT NULL CHECK (quarter BETWEEN 1 AND 4),
  year SMALLINT NOT NULL,
  CHECK (EXTRACT(DAY FROM month_start) = 1),
  CHECK (month = EXTRACT(MONTH FROM month_start)),
  CHECK (year = EXTRACT(YEAR FROM month_start)),
  CHECK (quarter = EXTRACT(QUARTER FROM month_start)),
  CHECK (date_key = year * 100 + month)
);

CREATE TABLE dim_genre (
  genre_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_name VARCHAR(100) NOT NULL UNIQUE
); -- Type 1: overwrite label corrections; retain the key.

CREATE TABLE dim_developer (
  developer_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  developer_id INTEGER NOT NULL, -- stable developer/publisher relationship ID from a curated lookup
  developer_name VARCHAR(255) NOT NULL,
  publisher VARCHAR(255) NOT NULL,
  valid_from TIMESTAMP NOT NULL,
  valid_to TIMESTAMP,
  is_current BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (developer_id, valid_from),
  CHECK (valid_to IS NULL OR valid_to > valid_from),
  CHECK (is_current = (valid_to IS NULL))
);
CREATE UNIQUE INDEX one_current_developer_per_id
  ON dim_developer (developer_id) WHERE is_current;

CREATE TABLE fact_game_activity (
  game_key INTEGER NOT NULL REFERENCES dim_game(game_key),
  date_key INTEGER NOT NULL REFERENCES dim_date(date_key),
  genre_key INTEGER NOT NULL REFERENCES dim_genre(genre_key),
  developer_key INTEGER NOT NULL REFERENCES dim_developer(developer_key),
  avg_players DECIMAL(14,2) NOT NULL CHECK (avg_players >= 0),
  peak_players INTEGER NOT NULL CHECK (peak_players >= 0),
  player_gain DECIMAL(14,2), -- NULL for the first observed month / missing predecessor
  player_change_percentage DECIMAL(10,2), -- percent change, e.g. 1.19 means 1.19%
  PRIMARY KEY (game_key, date_key),
  CHECK (peak_players >= avg_players)
);
-- ETL/dbt must additionally test one fact per (appid, month_start),
-- even if multiple SCD game versions exist. SCD windows must not overlap.
